#!/usr/bin/env bash

# Exit on error
set -e

ZSH_DIR="$HOME/.zsh"
FAST_TERMINAL_ZSH="$ZSH_DIR/fast_terminal.zsh"
ZSHRC="$HOME/.zshrc"

# Print colored output
info() { echo -e "\033[1;34m[INFO]\033[0m $1"; }
success() { echo -e "\033[1;32m[SUCCESS]\033[0m $1"; }
warning() { echo -e "\033[1;33m[WARNING]\033[0m $1"; }

info "Setting up the fast terminal environment in $ZSH_DIR..."

# 1. Create the base directory
mkdir -p "$ZSH_DIR"

# Helper function to clone or update a git repository
clone_plugin() {
    local repo_url=$1
    local target_dir=$2

    if [ -d "$target_dir/.git" ]; then
        info "Plugin $(basename "$target_dir") already exists. Skipping clone."
    else
        info "Cloning $(basename "$target_dir")..."
        git clone -q "$repo_url" "$target_dir"
        success "Cloned $(basename "$target_dir")."
    fi
}

# Write stdin to a file only if the content differs, so re-runs report
# accurately. Sets MANAGED_FILE_CHANGED=1 if created/updated, 0 if untouched.
write_managed_file() {
    local dest=$1
    local tmp
    tmp="$(mktemp)"
    cat > "$tmp"
    if cmp -s "$tmp" "$dest" 2>/dev/null; then
        rm -f "$tmp"
        info "$dest is already up to date."
        MANAGED_FILE_CHANGED=0
    else
        mv "$tmp" "$dest"
        chmod 644 "$dest"
        success "Generated $dest."
        MANAGED_FILE_CHANGED=1
    fi
}

# 2. Install fzf binary if missing
if ! command -v fzf &> /dev/null; then
    info "Installing fzf binary..."
    if [ ! -d "$HOME/.fzf" ]; then
        git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME/.fzf"
    fi
    "$HOME/.fzf/install" --all --no-bash --no-fish --no-update-rc
    success "Installed fzf."
else
    info "fzf binary is already installed."
fi

# 3. Clone plugins and prompt
info "Installing ZSH plugins and Pure prompt..."
clone_plugin "https://github.com/Aloxaf/fzf-tab" "$ZSH_DIR/fzf-tab"
clone_plugin "https://github.com/zsh-users/zsh-autosuggestions" "$ZSH_DIR/zsh-autosuggestions"
clone_plugin "https://github.com/zsh-users/zsh-syntax-highlighting" "$ZSH_DIR/zsh-syntax-highlighting"
clone_plugin "https://github.com/sindresorhus/pure" "$ZSH_DIR/pure"

# 4. Create the self-contained ZSH configuration file
info "Checking $FAST_TERMINAL_ZSH..."

write_managed_file "$FAST_TERMINAL_ZSH" << 'EOF'
# Fast terminal configuration from: https://mijndertstuij.nl/posts/life-is-too-short-for-a-slow-terminal/

# Enable extended_glob for compinit cache check
setopt extended_glob

# 1. Pure Prompt (Async prompt)
fpath=(~/.zsh/pure $fpath)

# 2. Caching completions
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qNmh-24) ]]; then
  compinit -C
else
  compinit
fi

# Initialize Pure prompt
autoload -U promptinit; promptinit
prompt pure

# 3. fzf binary configuration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# 4. Plugins
# It is recommended to load syntax highlighting last
source ~/.zsh/fzf-tab/fzf-tab.plugin.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# 4. Lazy-loading nvm
export NVM_DIR="$HOME/.nvm"
nvm() {
  unset -f nvm
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh" --no-use
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
  nvm "$@"
}

# 5. Lazy-loading kubectl
kubectl() {
    command kubectl "$@"
    local ret=$?
    if [[ -z $KUBECTL_COMPLETE ]]; then
        source <(command kubectl completion zsh)
        KUBECTL_COMPLETE=1
    fi
    return $ret
}
EOF

# 4. Source the configuration in ~/.zshrc
info "Checking $ZSHRC..."

touch "$ZSHRC"

if grep -q "source ~/.zsh/fast_terminal.zsh" "$ZSHRC"; then
    info "The fast terminal configuration is already sourced in $ZSHRC."
else
    info "Adding source directive to $ZSHRC..."
    echo "" >> "$ZSHRC"
    echo "# Load fast terminal configuration" >> "$ZSHRC"
    echo "source ~/.zsh/fast_terminal.zsh" >> "$ZSHRC"
    success "Appended to $ZSHRC."
fi

# 5. Configure tmux theme (terminal-independent; tmux draws its own status
# bar, pane borders, and messages, so it needs matching colors of its own)
if command -v tmux &> /dev/null; then
    TMUX_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
    TMUX_FAST_CONF="$TMUX_DIR/fast-terminal.conf"
    TMUX_CONF="$HOME/.tmux.conf"
    # Prefer an existing XDG-style tmux.conf if that is what the user uses
    if [ ! -f "$TMUX_CONF" ] && [ -f "$TMUX_DIR/tmux.conf" ]; then
        TMUX_CONF="$TMUX_DIR/tmux.conf"
    fi

    info "Configuring tmux theme..."
    mkdir -p "$TMUX_DIR"

    write_managed_file "$TMUX_FAST_CONF" << 'EOF'
# Fast terminal tmux theme (generated by setup_fast_terminal.sh)
# Snazzy palette on the #1b1b1b (Vine Black) custom background

# True color support so the terminal theme renders correctly inside tmux
set -g default-terminal "tmux-256color"
# Guarded append so re-sourcing this file never accumulates duplicate entries
%if #{==:#{m:*RGB*,#{terminal-overrides}},0}
set -ga terminal-overrides ",*:RGB"
%endif

# Status bar
set -g status-style "bg=#1b1b1b,fg=#eff0eb"
set -g status-left "#[fg=#5af78e,bold] #S "
set -g status-right "#[fg=#57c7ff] %H:%M "
setw -g window-status-style "fg=#a5a5a9"
setw -g window-status-current-style "fg=#ff6ac1,bold"
setw -g window-status-activity-style "fg=#f3f99d"

# Pane borders
set -g pane-border-style "fg=#34353e"
set -g pane-active-border-style "fg=#57c7ff"

# Messages and command prompt
set -g message-style "bg=#1b1b1b,fg=#f3f99d"
set -g message-command-style "bg=#1b1b1b,fg=#f3f99d"

# Copy mode selection
setw -g mode-style "bg=#3e404e,fg=#eff0eb"
EOF

    touch "$TMUX_CONF"
    if grep -q "fast-terminal.conf" "$TMUX_CONF"; then
        info "tmux config already sources fast-terminal.conf."
    else
        info "Adding source-file directive to $TMUX_CONF..."
        printf '\n# Load fast terminal theme\nsource-file %s\n' "$TMUX_FAST_CONF" >> "$TMUX_CONF"
        success "Appended to $TMUX_CONF."
    fi

    # Apply immediately if the theme changed and a tmux server is running
    if [ "$MANAGED_FILE_CHANGED" = 1 ] && tmux list-sessions &> /dev/null; then
        tmux source-file "$TMUX_FAST_CONF"
        info "Reloaded theme in the running tmux server."
    fi
fi

# 6. Configure the terminal emulator (iTerm2 or Ghostty)
configure_iterm() {
    info "Configuring iTerm2 profile..."
    local dest_dir="$HOME/Library/Application Support/iTerm2/DynamicProfiles"
    local profile_json
    if ! profile_json="$(/usr/bin/python3 -c '
import plistlib
import json
import urllib.request
import sys

url = "https://raw.githubusercontent.com/sindresorhus/iterm2-snazzy/main/Snazzy.itermcolors"
try:
    req = urllib.request.urlopen(url)
    colors = plistlib.loads(req.read())
except Exception as e:
    print(f"Failed to download Snazzy theme: {e}", file=sys.stderr)
    sys.exit(1)

# Set custom background color to #1b1b1b (Vine Black)
colors["Background Color"] = {
    "Alpha Component": 1.0,
    "Red Component": 27/255.0,
    "Green Component": 27/255.0,
    "Blue Component": 27/255.0,
    "Color Space": "sRGB"
}

profile = {
    "Name": "Fast Terminal",
    "Guid": "Fast-Terminal-Profile",
    "Cursor Type": 1,  # Vertical bar
    "Normal Font": "Menlo-Regular 12",
    "Use Separate Colors for Light and Dark Mode": False,
}
# Merge colors into profile
profile.update(colors)

print(json.dumps({"Profiles": [profile]}, indent=2))
')"; then
        warning "Could not build the iTerm2 profile (Snazzy theme download failed); skipping iTerm2 styling."
        return 0
    fi

    mkdir -p "$dest_dir"
    write_managed_file "$dest_dir/FastTerminal.json" <<< "$profile_json"
    local profile_changed=$MANAGED_FILE_CHANGED

    local default_changed=0
    if [ "$(defaults read com.googlecode.iterm2 "Default Bookmark Guid" 2>/dev/null)" = "Fast-Terminal-Profile" ]; then
        info "'Fast Terminal' is already the default iTerm2 profile."
    else
        info "Setting 'Fast Terminal' as the default iTerm2 profile..."
        defaults write com.googlecode.iterm2 "Default Bookmark Guid" "Fast-Terminal-Profile"
        default_changed=1
    fi

    if [ "$profile_changed" = 1 ] || [ "$default_changed" = 1 ]; then
        success "Configured iTerm2 profile 'Fast Terminal' (Snazzy theme, Menlo font, vertical cursor). Completely restart iTerm2 (Cmd+Q) to apply."
    else
        info "iTerm2 is already fully configured; nothing to change."
    fi
}

configure_ghostty() {
    local ghostty_dir="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty"
    local ghostty_conf="$ghostty_dir/config"
    local fast_conf="$ghostty_dir/fast-terminal.conf"

    info "Configuring Ghostty..."
    mkdir -p "$ghostty_dir"

    write_managed_file "$fast_conf" << 'EOF'
# Fast terminal configuration (generated by setup_fast_terminal.sh)
# Snazzy is bundled with Ghostty; explicit colors below override the theme
theme = Snazzy
# Custom background #1b1b1b (Vine Black)
background = 1b1b1b
font-family = Menlo
font-size = 12
cursor-style = bar
EOF

    local conf_changed=$MANAGED_FILE_CHANGED

    touch "$ghostty_conf"
    if grep -q "^config-file = fast-terminal.conf" "$ghostty_conf"; then
        info "Ghostty config already includes fast-terminal.conf."
    else
        info "Adding config-file directive to $ghostty_conf..."
        printf '\n# Load fast terminal configuration\nconfig-file = fast-terminal.conf\n' >> "$ghostty_conf"
        conf_changed=1
    fi

    if [ "$conf_changed" = 1 ]; then
        success "Configured Ghostty (Snazzy theme, Menlo font, vertical cursor). Reload its config (Cmd+Shift+,) or restart Ghostty to apply."
    else
        info "Ghostty is already fully configured; nothing to change."
    fi
}

# tmux masks TERM_PROGRAM; the tmux server still has the environment of the
# terminal it was started from, so ask it for the original value
TERMINAL_APP="$TERM_PROGRAM"
if [ -n "$TMUX" ] || [ "$TERMINAL_APP" = "tmux" ]; then
    TERMINAL_APP="$(tmux show-environment -g TERM_PROGRAM 2>/dev/null | cut -d= -f2-)"
fi

case "$TERMINAL_APP" in
    iTerm.app) configure_iterm ;;
    ghostty)   configure_ghostty ;;
    *) info "No supported terminal detected (TERM_PROGRAM='${TERM_PROGRAM:-unset}'); skipped iTerm2/Ghostty styling." ;;
esac
